package com.agentic.chatbot.generator;

import com.agentic.chatbot.llm.LlmClient;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Component
public class FunctionalTestGenerator {

    private static final Pattern FILE_BLOCK = Pattern.compile(
            "(?s)```(?:java)?\\s*\\n?//\\s*FILE:\\s*(.+?)\\n(.*?)```");

    private final LlmClient llmClient;

    public FunctionalTestGenerator(LlmClient llmClient) {
        this.llmClient = llmClient;
    }

    public List<Path> generate(String userStory, Path projectDir) throws IOException {
        StoryAnalyzer.Analysis analysis = StoryAnalyzer.analyze(userStory);
        List<Path> written = new ArrayList<>();

        if (llmClient.isAvailable()) {
            try {
                String system = """
                        You are a QA automation engineer specializing in Java functional tests.
                        Write Spring MockMvc end-to-end style functional tests (no real browser required).
                        Optionally include Selenium stubs commented out.
                        Output ONLY markdown fences starting with // FILE: relative/path under src/test/java
                        Name the class *FunctionalTest.
                        """;
                String content = llmClient.complete(system, "User story:\n" + userStory);
                written.addAll(writeFences(content, projectDir));
                if (!written.isEmpty()) {
                    return written;
                }
            } catch (Exception ignored) {
            }
        }

        written.add(writeOfflineFunctionalTest(analysis, projectDir));
        return written;
    }

    private Path writeOfflineFunctionalTest(StoryAnalyzer.Analysis a, Path projectDir) throws IOException {
        String pkgPath = a.packageName().replace('.', '/');
        Path testFile = projectDir.resolve(
                "src/test/java/" + pkgPath + "/" + a.classPrefix() + "FunctionalTest.java");
        Files.createDirectories(testFile.getParent());
        String route = "/" + a.featureName().toLowerCase().replaceAll("[^a-z0-9-]", "");

        String body = """
                package %s;

                import org.junit.jupiter.api.DisplayName;
                import org.junit.jupiter.api.Test;
                import org.springframework.beans.factory.annotation.Autowired;
                import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
                import org.springframework.boot.test.context.SpringBootTest;
                import org.springframework.test.web.servlet.MockMvc;

                import static org.hamcrest.Matchers.containsString;
                import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
                import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
                import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

                /**
                 * Functional tests generated by Bot 3 (Functional Testing Agent).
                 * These exercise the HTTP + view flow end-to-end via MockMvc.
                 */
                @SpringBootTest(classes = com.generated.app.GeneratedAppApplication.class)
                @AutoConfigureMockMvc
                class %sFunctionalTest {

                    @Autowired
                    private MockMvc mockMvc;

                    @Test
                    @DisplayName("User can open the generated screen")
                    void openScreen() throws Exception {
                        mockMvc.perform(get("%s"))
                                .andExpect(status().isOk())
                                .andExpect(content().string(containsString("field1")));
                    }

                    @Test
                    @DisplayName("User can submit the primary form flow")
                    void submitPrimaryFlow() throws Exception {
                        mockMvc.perform(post("%s")
                                        .param("field1", "demo-user")
                                        .param("field2", "demo-pass"))
                                .andExpect(result -> {
                                    int status = result.getResponse().getStatus();
                                    if (status >= 500) {
                                        throw new AssertionError("Unexpected server error: " + status);
                                    }
                                });
                    }
                }
                """.formatted(a.packageName(), a.classPrefix(), route, route);

        if (a.type() == StoryAnalyzer.ScreenType.LOGIN) {
            body = """
                    package %s;

                    import org.junit.jupiter.api.DisplayName;
                    import org.junit.jupiter.api.Test;
                    import org.springframework.beans.factory.annotation.Autowired;
                    import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
                    import org.springframework.boot.test.context.SpringBootTest;
                    import org.springframework.test.web.servlet.MockMvc;

                    import static org.hamcrest.Matchers.containsString;
                    import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
                    import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
                    import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

                    /**
                     * Functional tests generated by Bot 3 (Functional Testing Agent).
                     */
                    @SpringBootTest(classes = com.generated.app.GeneratedAppApplication.class)
                    @AutoConfigureMockMvc
                    class %sFunctionalTest {

                        @Autowired
                        private MockMvc mockMvc;

                        @Test
                        @DisplayName("Login page is reachable")
                        void loginPageReachable() throws Exception {
                            mockMvc.perform(get("%s"))
                                    .andExpect(status().isOk())
                                    .andExpect(content().string(containsString("Sign in with Google")));
                        }

                        @Test
                        @DisplayName("Valid credentials redirect to instructed page")
                        void validLoginReachesDestination() throws Exception {
                            mockMvc.perform(post("%s")
                                            .param("field1", "alice")
                                            .param("field2", "secret"))
                                    .andExpect(redirectedUrl("%s"));

                            mockMvc.perform(get("%s"))
                                    .andExpect(status().isOk())
                                    .andExpect(content().string(containsString("Welcome")));
                        }

                        @Test
                        @DisplayName("Blank credentials stay on login with error")
                        void blankCredentialsShowError() throws Exception {
                            mockMvc.perform(post("%s"))
                                    .andExpect(status().isOk())
                                    .andExpect(model().attributeExists("error"));
                        }
                    }
                    """.formatted(a.packageName(), a.classPrefix(), route, route,
                    a.redirectPath() != null ? a.redirectPath() : "/dashboard",
                    a.redirectPath() != null ? a.redirectPath() : "/dashboard",
                    route);
        }

        Files.writeString(testFile, body, StandardCharsets.UTF_8);
        return testFile;
    }

    private List<Path> writeFences(String content, Path projectDir) throws IOException {
        List<Path> paths = new ArrayList<>();
        Matcher m = FILE_BLOCK.matcher(content);
        while (m.find()) {
            Path out = projectDir.resolve(m.group(1).trim().replace('\\', '/'));
            Files.createDirectories(out.getParent());
            Files.writeString(out, m.group(2).strip() + System.lineSeparator(), StandardCharsets.UTF_8);
            paths.add(out);
        }
        return paths;
    }
}
